export default[
    {
    "login": "Aviksaikat",
    "id": 31238298,
    "node_id": "MDQ6VXNlcjMxMjM4Mjk4",
    "avatar_url": "https://avatars.githubusercontent.com/u/31238298?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aviksaikat",
    "html_url": "https://github.com/Aviksaikat",
    "followers_url": "https://api.github.com/users/Aviksaikat/followers",
    "following_url": "https://api.github.com/users/Aviksaikat/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aviksaikat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aviksaikat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aviksaikat/subscriptions",
    "organizations_url": "https://api.github.com/users/Aviksaikat/orgs",
    "repos_url": "https://api.github.com/users/Aviksaikat/repos",
    "events_url": "https://api.github.com/users/Aviksaikat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aviksaikat/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "himanshuWeb007",
    "id": 65900331,
    "node_id": "MDQ6VXNlcjY1OTAwMzMx",
    "avatar_url": "https://avatars.githubusercontent.com/u/65900331?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/himanshuWeb007",
    "html_url": "https://github.com/himanshuWeb007",
    "followers_url": "https://api.github.com/users/himanshuWeb007/followers",
    "following_url": "https://api.github.com/users/himanshuWeb007/following{/other_user}",
    "gists_url": "https://api.github.com/users/himanshuWeb007/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/himanshuWeb007/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/himanshuWeb007/subscriptions",
    "organizations_url": "https://api.github.com/users/himanshuWeb007/orgs",
    "repos_url": "https://api.github.com/users/himanshuWeb007/repos",
    "events_url": "https://api.github.com/users/himanshuWeb007/events{/privacy}",
    "received_events_url": "https://api.github.com/users/himanshuWeb007/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "code-sanket",
    "id": 66024385,
    "node_id": "MDQ6VXNlcjY2MDI0Mzg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/66024385?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/code-sanket",
    "html_url": "https://github.com/code-sanket",
    "followers_url": "https://api.github.com/users/code-sanket/followers",
    "following_url": "https://api.github.com/users/code-sanket/following{/other_user}",
    "gists_url": "https://api.github.com/users/code-sanket/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/code-sanket/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/code-sanket/subscriptions",
    "organizations_url": "https://api.github.com/users/code-sanket/orgs",
    "repos_url": "https://api.github.com/users/code-sanket/repos",
    "events_url": "https://api.github.com/users/code-sanket/events{/privacy}",
    "received_events_url": "https://api.github.com/users/code-sanket/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "printf-twinkle",
    "id": 67370801,
    "node_id": "MDQ6VXNlcjY3MzcwODAx",
    "avatar_url": "https://avatars.githubusercontent.com/u/67370801?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/printf-twinkle",
    "html_url": "https://github.com/printf-twinkle",
    "followers_url": "https://api.github.com/users/printf-twinkle/followers",
    "following_url": "https://api.github.com/users/printf-twinkle/following{/other_user}",
    "gists_url": "https://api.github.com/users/printf-twinkle/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/printf-twinkle/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/printf-twinkle/subscriptions",
    "organizations_url": "https://api.github.com/users/printf-twinkle/orgs",
    "repos_url": "https://api.github.com/users/printf-twinkle/repos",
    "events_url": "https://api.github.com/users/printf-twinkle/events{/privacy}",
    "received_events_url": "https://api.github.com/users/printf-twinkle/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "kumarAyush37",
    "id": 71386671,
    "node_id": "MDQ6VXNlcjcxMzg2Njcx",
    "avatar_url": "https://avatars.githubusercontent.com/u/71386671?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kumarAyush37",
    "html_url": "https://github.com/kumarAyush37",
    "followers_url": "https://api.github.com/users/kumarAyush37/followers",
    "following_url": "https://api.github.com/users/kumarAyush37/following{/other_user}",
    "gists_url": "https://api.github.com/users/kumarAyush37/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kumarAyush37/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kumarAyush37/subscriptions",
    "organizations_url": "https://api.github.com/users/kumarAyush37/orgs",
    "repos_url": "https://api.github.com/users/kumarAyush37/repos",
    "events_url": "https://api.github.com/users/kumarAyush37/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kumarAyush37/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "omraakhtarit2020",
    "id": 79746003,
    "node_id": "MDQ6VXNlcjc5NzQ2MDAz",
    "avatar_url": "https://avatars.githubusercontent.com/u/79746003?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/omraakhtarit2020",
    "html_url": "https://github.com/omraakhtarit2020",
    "followers_url": "https://api.github.com/users/omraakhtarit2020/followers",
    "following_url": "https://api.github.com/users/omraakhtarit2020/following{/other_user}",
    "gists_url": "https://api.github.com/users/omraakhtarit2020/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/omraakhtarit2020/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/omraakhtarit2020/subscriptions",
    "organizations_url": "https://api.github.com/users/omraakhtarit2020/orgs",
    "repos_url": "https://api.github.com/users/omraakhtarit2020/repos",
    "events_url": "https://api.github.com/users/omraakhtarit2020/events{/privacy}",
    "received_events_url": "https://api.github.com/users/omraakhtarit2020/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "adarsh112221",
    "id": 82704485,
    "node_id": "MDQ6VXNlcjgyNzA0NDg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/82704485?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adarsh112221",
    "html_url": "https://github.com/adarsh112221",
    "followers_url": "https://api.github.com/users/adarsh112221/followers",
    "following_url": "https://api.github.com/users/adarsh112221/following{/other_user}",
    "gists_url": "https://api.github.com/users/adarsh112221/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adarsh112221/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adarsh112221/subscriptions",
    "organizations_url": "https://api.github.com/users/adarsh112221/orgs",
    "repos_url": "https://api.github.com/users/adarsh112221/repos",
    "events_url": "https://api.github.com/users/adarsh112221/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adarsh112221/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "alokpaul5",
    "id": 91766242,
    "node_id": "U_kgDOBXg94g",
    "avatar_url": "https://avatars.githubusercontent.com/u/91766242?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/alokpaul5",
    "html_url": "https://github.com/alokpaul5",
    "followers_url": "https://api.github.com/users/alokpaul5/followers",
    "following_url": "https://api.github.com/users/alokpaul5/following{/other_user}",
    "gists_url": "https://api.github.com/users/alokpaul5/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/alokpaul5/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/alokpaul5/subscriptions",
    "organizations_url": "https://api.github.com/users/alokpaul5/orgs",
    "repos_url": "https://api.github.com/users/alokpaul5/repos",
    "events_url": "https://api.github.com/users/alokpaul5/events{/privacy}",
    "received_events_url": "https://api.github.com/users/alokpaul5/received_events",
    "type": "User",
    "site_admin": false
    }
    ]